Fixes #2
brunch/deps-install pull request #3
Opened 2017-06-02 22:45 UTC by r3liant

This fixes issue #2 by using cross-spawn. Verified to work with both yarn and npm.

2017-06-03 10:30 UTC, shvaikalesh requested changes
`cross-spawn` is too heavy. Dropping Node's < 6 is ok.

2017-06-05 01:54 UTC, r3liant commented
Done. Since shell = false was known to work for UNIX platforms I also added a conditional to check if the platform was windows. I would recommend bumping the version and also updating brunch/brunch as that is how I found this problem.

2017-06-05 09:09 UTC, shvaikalesh commented on index.js
> +  const useShell = process.platform === "win32" ? true : false;
Let's drop unneeded ternary here:
```js
const shell = process.platform === 'win32'
return !cp.spawnSync(cmd, ['--version'], {shell}).error;
```

2017-06-05 09:09 UTC, shvaikalesh commented
And please let's not include `yarn.lock`

2017-06-05 13:58 UTC, r3liant commented
Alrighty. I already removed yarn.lock and added it the .gitignore since devs may leave it in there accidentally while testing. (What I did)

2017-06-05 15:02 UTC, merged

2017-06-05 15:03 UTC, shvaikalesh commented
Thanks for the PR and patience while making changes, @r3liant.

@paulmillr could you please release patch?